image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - docker login -u "$HUB_USERNAME" -p "$HUB_PASSWORD" $HUB_REGISTRY

build-master:
  stage: build
  script:
    - docker build --no-cache --pull -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
    - master

build:
  stage: build
  script:
    - CI_COMMIT_TAG=$CI_COMMIT_REF_NAME
    - if [ "${CI_COMMIT_REF_NAME:0:1}" == "v" ]; then
        CI_COMMIT_TAG=${CI_COMMIT_REF_NAME:1};
      fi
    - docker build --no-cache --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
    - if [ "${CI_COMMIT_REF_NAME:0:1}" == "v" ]; then
        docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" "joramk/ubi8-httpd-php:$CI_COMMIT_TAG";
        docker push "joramk/ubi8-httpd-php:${CI_COMMIT_REF_NAME:1}";
      fi
    - case "$CI_COMMIT_TAG" in *\.*\.*)
        CI_SHORT_TAG=`echo "$CI_COMMIT_TAG" | sed -e 's/\([0-9.]\.[0-9.]\).*/\1/'`;
        docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" "joramk/ubi8-httpd-php:$CI_SHORT_TAG";
        docker push "joramk/ubi8-httpd-php:$CI_SHORT_TAG";
      esac
    - docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" "joramk/ubi8-httpd-php:$CI_COMMIT_TAG"
    - docker push "joramk/ubi8-httpd-php:$CI_COMMIT_TAG"
  except:
    - master

